name: Debugging Demo

on:
  workflow_dispatch:
  push:

env:
  USER_1: "foo-user"
  USER_2: "bar-user"

jobs:
  debug_job:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Checkout Repo
        uses: actions/checkout@v4

      - name: Step 2 - Set USER_1 as USERNAME
        run: |
          echo "USERNAME=${{ env.USER_1 }}" >> $GITHUB_ENV
          echo "Setting USERNAME to: ${{ env.USER_1 }}"

      - name: Step 3 - Printing USERNAME
        run: |
          echo "Printing USERNAME env variable from previous step:"
          echo "Username: ${{ env.USERNAME }}"
          exit 1 
      - name: Step 4 - Printing USER_2
        run: |
          echo "USER_2: ${{ env.USER_2 }}"